package exceptionHandling;

public class exception5 {
	
	public static void main(String[] args)
	{
//		int a = 100;
//		int output = 0;
//		
//		try
//		{
//			output= a/2;       // take divide by 2 also
//			
//		}
//		catch (ArithmeticException ae) 
//		{
//			System.out.println("finally");
//		}
//		
//		
//		System.out.println(output);
		
		String s = null;
		try 
		{
			System.out.println(s.length());
		}
		catch(Exception e) 
		{
			
			
		}
		
		
		
		
		
		
}
}
